### ISSUE TITLE
Correção - Atualização SDK de 45 para 48

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/api-maisum#34]

**Comment by rafaeljcg20** [comment]
Solução alternativa

1 Instalar o APK Pure no Android do celular e através dessa central de software, instalar a versão anterior do Expor SKd45
2 Baixar do site a versões anteriores do Expo https://m.apkpure.com/expo/host.exp.exponent/versions

**Comment by Jonaathan-Santos** [comment]
Atualização  para o SDK 48.0.0

Branch: hotfix/update-sdk

Instruções:

Baixar a branch, remover o diretório node_modules  na raiz do projeto (caso exista),
rodar o comando $npm install, depois rodar o comando $npm start -c

**Comment by rafaeljcg20** [comment]
Boa tarde Pessoal,

Infelizmente consegui encontrar um erro ao realizar o upload de foto na tela de Cadastrar Líder e peço que por favor possam ajustar(Principalmente @WarlenFerreira e @Jonaathan-Santos 

Passos para reproduzir o problema:
1 Entrei no sistema com o usuário admin@admin.com
2 Cliquei no menu Líderes
3 Cliquei na opção Alterar Líder
4 Cliquei no ícone de alterar foto e selecionei uma foto da galeria do celular
5 O sistema trocou a foto, porém exibiu uma mensagem dizendo que o atributo 'uri' do componente image-picker está depreciado.

Segue imagem abaixo do erro:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/ab029775-60b6-4b9f-97a6-95dd1aabf70e)

**Comment by rafaeljcg20** [comment]
**Erro ao inserir foto na tela de Adicionar Líder e Editar líder resolvido!**

**Comment by rafaeljcg20** [comment]
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/92e47681-bf22-4ec3-9056-fbaff755166b)

Foi identificado um novo erro ao clicar no botão "Sair" do app que impede o usuário de retornar para a tela de login e encerrar sua sessão.

**Comment by WarlenFerreira** [comment]
acabei de consertar o update sdk, com um reparo rápido para dar andamentos nas outras branch, foi criado outra branch chamada hotfix/update-sdk2.0, onde foi consertado o problema de sair e dos menus, criei outra poios a branch que está sendo refatorado pode demorar mais que o esperado para ser concluída

**Comment by rafaeljcg20** [comment]
Excelente tomada de decisão @WarlenFerreira e @Jonaathan-Santos e além disso fizeram exatamente como pede o nosso framework de trabalho Scrum e também agiram perfeitamente em relação as branchs

Vamos para Cima, agora estamos a 300km por hora!

Vou realizar o testes dos defeitos identificados e vou ficar na torcida para que possamos terminar essa demanda colocando em feito

= )

**Comment by rafaeljcg20** [comment]
Testando...

**Comment by rafaeljcg20** [comment]
Foi realizado o teste e tanto o erro de tentar adiconar um novo líder quanto o erro do botão Sair foram resolvidos na última correção.

**Comment by rafaeljcg20** [comment]
Porém achei outro erro que acredito que pode ter sido eu mesmo que gerei quando tentei arrumar a demanda de correção da validação do campo de líderes na útima sprint release/2.1.0 .

Passo a passo para reproduzir o problema:
Ao logar no aplicativo com um usuário que tenha perfil de Líder(Ao invés de Administrador), tentar cadastrar um novo Líder preenchendo o formulário completo e clicando no botão Adicionar... O sistema não realiza ação nenhuma e o esperado era que o sistema cadastrasse o novo líder e retornasse para a tela de Líder com a lista de líderes atualizada constando o novo líder que tentamos adicionar.

Segue a imagem do formulário preenchido:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/0f7ae90c-0292-4f11-a8ad-c6288a07df7f)

**Comment by rafaeljcg20** [comment]
O último erro já existia antes do começo da demanda e foi realizado acordo com a equipe/Squad para poder abrir outro item de backlog para essa correção.

O resto dos erros foram corrigidos e a demanda está considerada testada e finalizada.
