### ISSUE TITLE
Tela Adicionar Líder - Correção salvar novo líder - perfil líder

### ISSUE THREAD

**Issue by rafaeljcg20** [sara-nossa-terra/api-maisum#36]
Passo a passo para reproduzir o problema:
Ao logar no aplicativo com um usuário que tenha perfil de Líder(Ao invés de Administrador), tentar cadastrar um novo Líder preenchendo o formulário completo e clicando no botão Adicionar... O sistema não realiza ação nenhuma e o esperado era que o sistema cadastrasse o novo líder e retornasse para a tela de Líder com a lista de líderes atualizada constando o novo líder que tentamos adicionar.

Segue a imagem do formulário preenchido:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/0f7ae90c-0292-4f11-a8ad-c6288a07df7f)

**Comment by rafaeljcg20** [comment]
Passo a passo para reproduzir o problema:
Ao logar no aplicativo com um usuário que tenha perfil de Líder(Ao invés de Administrador), tentar cadastrar um novo Líder preenchendo o formulário completo e clicando no botão Adicionar... O sistema não realiza ação nenhuma e o esperado era que o sistema cadastrasse o novo líder e retornasse para a tela de Líder com a lista de líderes atualizada constando o novo líder que tentamos adicionar.

Segue a imagem do formulário preenchido:
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/0f7ae90c-0292-4f11-a8ad-c6288a07df7f)

**Comment by rafaeljcg20** [comment]
hotfix/tela-adicionar-lider-perfil-lider

**Comment by rafaeljcg20** [comment]
Codificação concluída.

Por favor, realizarem o teste.
@matheusz061df @Jonaathan-Santos @WarlenFerreira

**Comment by maiconrit** [comment]
testei a demanda e esta tudo certo passou nos testes
fluxo básico, vazio e cheio

**Comment by maiconrit** [comment]
não consegui fechar a demanda, por favor ajustar minhas permiçaoes  no Zenhub

**Comment by matheusz061df** [comment]
Teste realizado com sucesso, nenhum erro encotrado.
